---
name: Develop Frontend Living Style Guide

on:
  push:
    branches-ignore:
      - release
      - main
      - develop

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  dev-fe-lsg:
    name: Develop Frontend Living Style Guide
    runs-on: ubuntu-latest
    steps:
      - run: echo 'event name is:' ${{ github.event_name }} 
      - run: echo 'event type is:' ${{ github.event.action }} 
      - name: 'â˜ï¸ checkout repository'
        uses: actions/checkout@v3

      - name: 'ğŸ”  Verify Changed Frontend Living Style Guide Files'
        uses: tj-actions/changed-files@v23.1
        id: changed-frontend-living-style-guide-files
        with:
          files: |
            frontend/living-style-guide/**/*.scss

      - name: List all Living Style Guide changed files
        run: |
          for file in ${{ steps.changed-frontend-living-style-guide-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: 'Cache node_modules'
        if: steps.changed-frontend-living-style-guide-files.outputs.any_changed == 'true' || 'workflow_dispatch'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'ğŸ”§  Setup NodeJS 14.19.1'
        if: steps.changed-frontend-living-style-guide-files.outputs.any_changed == 'true' || 'workflow_dispatch'
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1

      - name: 'ğŸ”§  Install npm@latest'
        if: steps.changed-frontend-living-style-guide-files.outputs.any_changed == 'true' || 'workflow_dispatch'
        run: npm i -g npm@latest

      - name: 'ğŸ“¦  Install Frontend Living Style Guide Development dependencies'
        if: steps.changed-frontend-living-style-guide-files.outputs.any_changed == 'true' || 'workflow_dispatch'
        run: bash scripts/frontend-living-style-guide-install.bash

      - name: 'ğŸ”  Lint Frontend Living Style Guide'
        if: steps.changed-frontend-living-style-guide-files.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/frontend-living-style-guide-lint.bash

      - name: 'ğŸ§ª  Test Frontend Living Style Guide'
        if: steps.changed-frontend-living-style-guide-files.outputs.any_changed == 'true' && github.event_name == 'push'
        run: bash scripts/frontend-living-style-guide-test.bash

      - name: 'ğŸ› ï¸  Compile Frontend living-style-guide'
        if: (steps.changed-frontend-living-style-guide-files.outputs.any_changed == 'true' && github.event_name == 'pull_request') || 'workflow_dispatch'
        run: bash scripts/frontend-living-style-guide-compile.bash production